//! The compatibility gate for config.json: every fixture must load to exactly what v0.3.1's
//! `config::load()` produced (tests/fixtures/persisted/expected/, generated by running it).

use super::*;
use serde_json::Value;
use std::path::PathBuf;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/persisted")
}

/// Loads `src` the way the app does, from a scratch config directory.
fn load_fixture(src: &str) -> (Config, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    std::fs::copy(fixtures().join(src), dir.path().join("config.json")).unwrap();
    let r = load(dir.path());
    assert!(!r.missing);
    (r.config, dir)
}

fn slots(v: &Value) -> Vec<Slot> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|s| Slot {
            provider: s["provider"].as_str().unwrap().into(),
            window: s["window"].as_str().unwrap().into(),
        })
        .collect()
}

fn assert_matches_v031(cfg: &Config, expected: &str) {
    let text = std::fs::read_to_string(fixtures().join("expected").join(expected)).unwrap();
    let e: Value = serde_json::from_str(&text).unwrap();
    assert_eq!(cfg.port as u64, e["port"].as_u64().unwrap(), "port");
    assert_eq!(cfg.lang, e["lang"].as_str().unwrap(), "lang");
    assert_eq!(cfg.notch_y, e["notch_y"].as_f64().unwrap(), "notch_y");
    assert_eq!(cfg.scale, e["scale"].as_f64().unwrap(), "scale");
    assert_eq!(cfg.tray_mode.as_str(), e["tray_mode"].as_str().unwrap(), "tray_mode");
    assert_eq!(cfg.tray_slots, slots(&e["tray_slots"]), "tray_slots");
    assert_eq!(cfg.notch_slots, slots(&e["notch_slots"]), "notch_slots");
    assert_eq!(cfg.notch_visible, e["notch_visible"].as_bool().unwrap(), "notch_visible");
    assert_eq!(cfg.tray_visible, e["tray_visible"].as_bool().unwrap(), "tray_visible");
}

#[test]
fn every_fixture_loads_like_v031() {
    for (src, expected) in [
        ("v0.3.1/config.json", "v0.3.1-config.json"),
        ("legacy/config-pre-slots.json", "config-pre-slots.json"),
        ("legacy/config-port-only.json", "config-port-only.json"),
        ("legacy/config-both-hidden.json", "config-both-hidden.json"),
        ("legacy/config-scale-out-of-range.json", "config-scale-out-of-range.json"),
        ("legacy/config-unknown-keys.json", "config-unknown-keys.json"),
    ] {
        let (cfg, _dir) = load_fixture(src);
        assert_matches_v031(&cfg, expected);
    }
}

#[test]
fn saving_and_reloading_changes_nothing() {
    let (cfg, dir) = load_fixture("v0.3.1/config.json");
    save(dir.path(), &cfg).unwrap();
    let again = load(dir.path()).config;
    assert_eq!(again, cfg);
    assert_matches_v031(&again, "v0.3.1-config.json");
}

#[test]
fn keys_this_version_does_not_use_survive_a_save() {
    let (cfg, dir) = load_fixture("legacy/config-unknown-keys.json");
    save(dir.path(), &cfg).unwrap();
    let text = std::fs::read_to_string(dir.path().join("config.json")).unwrap();
    let doc: Value = serde_json::from_str(&text).unwrap();
    assert_eq!(doc["future_setting"]["x"], 1);
    // v0.3's own fields stay too, so going back to v0.3 still finds them
    let (cfg, dir) = load_fixture("v0.3.1/config.json");
    save(dir.path(), &cfg).unwrap();
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(dir.path().join("config.json")).unwrap()).unwrap();
    assert_eq!(doc["tray_providers"], serde_json::json!(["claude", "claude"]));
    assert_eq!(doc["bar_x"], Value::Null);
    assert!(doc.get("bar_x").is_some());
}

#[test]
fn setting_slots_keeps_the_v03_provider_lists_in_step() {
    let (mut cfg, dir) = load_fixture("v0.3.1/config.json");
    cfg.set_tray_slots(vec![Slot { provider: "codex".into(), window: String::new() }]);
    cfg.set_notch_slots(vec![]);
    save(dir.path(), &cfg).unwrap();
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(dir.path().join("config.json")).unwrap()).unwrap();
    assert_eq!(doc["tray_providers"], serde_json::json!(["codex"]));
    assert_eq!(doc["notch_providers"], serde_json::json!([]));
}

#[test]
fn the_theme_is_only_written_once_chosen() {
    // v0.3 never wrote one: it loads as system and a save does not add the key
    let (cfg, dir) = load_fixture("v0.3.1/config.json");
    assert_eq!(cfg.theme, Theme::System);
    save(dir.path(), &cfg).unwrap();
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(dir.path().join("config.json")).unwrap()).unwrap();
    assert!(doc.get("theme").is_none());
    // A chosen theme round-trips; an unknown one follows the system
    save(dir.path(), &Config { theme: Theme::Dark, ..cfg.clone() }).unwrap();
    assert_eq!(load(dir.path()).config.theme, Theme::Dark);
    assert_eq!(Theme::parse("sepia"), Theme::System);
}

#[test]
fn collapsing_is_on_unless_turned_off_and_only_off_is_written() {
    let (cfg, dir) = load_fixture("v0.3.1/config.json");
    assert!(cfg.notch_collapse);
    save(dir.path(), &cfg).unwrap();
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(dir.path().join("config.json")).unwrap()).unwrap();
    assert!(doc.get("notch_collapse").is_none());
    save(dir.path(), &Config { notch_collapse: false, ..cfg }).unwrap();
    assert!(!load(dir.path()).config.notch_collapse);
}

#[test]
fn the_port_stays_a_top_level_key_the_hook_can_scan() {
    let dir = tempfile::tempdir().unwrap();
    save(dir.path(), &Config { port: 49001, ..Config::default() }).unwrap();
    let text = std::fs::read_to_string(dir.path().join("config.json")).unwrap();
    assert!(text.contains("\"port\": 49001"));
}

#[test]
fn a_truncated_file_is_quarantined_not_overwritten() {
    let dir = tempfile::tempdir().unwrap();
    let original = std::fs::read(fixtures().join("legacy/config-truncated.json")).unwrap();
    std::fs::write(dir.path().join("config.json"), &original).unwrap();
    let r = load(dir.path());
    assert!(!r.missing, "an unreadable file must not count as missing, or defaults get saved");
    assert!(r.quarantined.is_some());
    assert_eq!(r.config, Config::default());
    let aside: Vec<_> = std::fs::read_dir(dir.path())
        .unwrap()
        .map(|e| e.unwrap().file_name().into_string().unwrap())
        .collect();
    assert_eq!(aside.len(), 1);
    assert!(aside[0].starts_with("config.json.unreadable-"));
    assert_eq!(std::fs::read(dir.path().join(&aside[0])).unwrap(), original);
}

#[test]
fn no_file_is_missing_with_new_install_defaults() {
    let dir = tempfile::tempdir().unwrap();
    let r = load(dir.path());
    assert!(r.missing);
    assert_eq!(r.config.tray_mode, TrayMode::Numbers);
    assert_eq!(r.config.tray_slots.len(), 2);
}
